// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CreateProfileReducer from "../create_profile_reducer";
import CreateRoomReducer from "../create_room_reducer";
import JoinRoomReducer from "../join_room_reducer";
import MakeRoomPermanentReducer from "../make_room_permanent_reducer";
import ProfileSetAvatarReducer from "../profile_set_avatar_reducer";
import ProfileSetNameReducer from "../profile_set_name_reducer";

export type CreateProfileParams = __Infer<typeof CreateProfileReducer>;
export type CreateRoomParams = __Infer<typeof CreateRoomReducer>;
export type JoinRoomParams = __Infer<typeof JoinRoomReducer>;
export type MakeRoomPermanentParams = __Infer<typeof MakeRoomPermanentReducer>;
export type ProfileSetAvatarParams = __Infer<typeof ProfileSetAvatarReducer>;
export type ProfileSetNameParams = __Infer<typeof ProfileSetNameReducer>;

