// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CancelActiveSessionsUserReducer from "../cancel_active_sessions_user_reducer";
import StartNewSessionReducer from "../start_new_session_reducer";
import SubmitMessageReducer from "../submit_message_reducer";

export type CancelActiveSessionsUserParams = __Infer<typeof CancelActiveSessionsUserReducer>;
export type StartNewSessionParams = __Infer<typeof StartNewSessionReducer>;
export type SubmitMessageParams = __Infer<typeof SubmitMessageReducer>;

