// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

// The tagged union or sum type for the algebraic type `Avatar`.
export const Avatar = __t.enum("Avatar", {
  Alice: __t.unit(),
  Bob: __t.unit(),
  Charlie: __t.unit(),
  Diana: __t.unit(),
  Eve: __t.unit(),
  Frank: __t.unit(),
  Grace: __t.unit(),
  Henry: __t.unit(),
  Ivy: __t.unit(),
  Jack: __t.unit(),
  Karen: __t.unit(),
  Leo: __t.unit(),
  Maria: __t.unit(),
  Nora: __t.unit(),
  Oscar: __t.unit(),
  Paul: __t.unit(),
  Quinn: __t.unit(),
  Ruby: __t.unit(),
  Steve: __t.unit(),
  Tina: __t.unit(),
  FromName: __t.unit(),
  FromIdentity: __t.unit(),
});
export type Avatar = __Infer<typeof Avatar>;

export const DeleteRoom = __t.object("DeleteRoom", {
  roomId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type DeleteRoom = __Infer<typeof DeleteRoom>;

export const OngoingVote = __t.object("OngoingVote", {
  id: __t.u64(),
  roomId: __t.u64(),
  participantId: __t.u64(),
  chosenCard: __t.string(),
});
export type OngoingVote = __Infer<typeof OngoingVote>;

export const Participant = __t.object("Participant", {
  id: __t.u64(),
  identity: __t.identity(),
  roomId: __t.u64(),
  name: __t.string(),
  get avatar() {
    return Avatar;
  },
  get role() {
    return ParticipantRole;
  },
});
export type Participant = __Infer<typeof Participant>;

// The tagged union or sum type for the algebraic type `ParticipantRole`.
export const ParticipantRole = __t.enum("ParticipantRole", {
  Moderator: __t.unit(),
  Player: __t.unit(),
  Spectator: __t.unit(),
});
export type ParticipantRole = __Infer<typeof ParticipantRole>;

export const Participation = __t.object("Participation", {
  connectionId: __t.connectionId(),
  participantId: __t.u64(),
});
export type Participation = __Infer<typeof Participation>;

export const Profile = __t.object("Profile", {
  identity: __t.identity(),
  name: __t.string(),
  get avatar() {
    return Avatar;
  },
});
export type Profile = __Infer<typeof Profile>;

export const Room = __t.object("Room", {
  id: __t.u64(),
  code: __t.string(),
  permanent: __t.bool(),
});
export type Room = __Infer<typeof Room>;

export const RoomRevealOutcome = __t.object("RoomRevealOutcome", {
  roomId: __t.u64(),
  timestamp: __t.timestamp(),
  get votes() {
    return __t.array(RoomRevealVote);
  },
});
export type RoomRevealOutcome = __Infer<typeof RoomRevealOutcome>;

export const RoomRevealVote = __t.object("RoomRevealVote", {
  participantId: __t.u64(),
  participantName: __t.string(),
  chosenCardId: __t.string(),
  chosenCardName: __t.string(),
});
export type RoomRevealVote = __Infer<typeof RoomRevealVote>;

