// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  SessionState,
  Message,
} from "./types";


export default __t.row({
  get ghostMessages() {
    return __t.array(Message).name("ghost_messages");
  },
  get initiatorMessages() {
    return __t.array(Message).name("initiator_messages");
  },
  get state() {
    return SessionState;
  },
  initiatedOn: __t.timestamp().name("initiated_on"),
  isComplete: __t.bool().name("is_complete"),
});
